{% set name = "muparserx" %}
{% set version = "4.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    git_url: https://github.com/beltoforion/muparserx.git
    git_rev: v{{ version }}


build:
  number: 0
  skip: true  # [linux32 or win32]

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux or osx]
    - vs2017_win-64          # [win]
    - cmake
  run:
    - icu

test:
  commands:
    - test -f ${PREFIX}/include/muparserx/mpParser.h # [unix]
    - if not exist %PREFIX%\\include\\muparserx\\mpParser.h exit 1 # [win]
about:
  home: http://muparserx.beltoforion.de/
  license: "BSD - Clause 2 Simplified"
  license_file: License.txt
  summary: A fast math parser C++ library
